# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86cc53cfb16c4916911dca582c7080fce721b024524a1fa2becfaf710349e5ba3b99a032cb9b04854be03cc403563665a91db533f83f206af49a820be043bc09

test:
  secret_key_base: 1216bdd134df670802530763ca1ad32879fc176064e7f4efab0909c7058bc858e71c20fed5d0d01879f52584aa6ff580663414e7e6f7d4f2111364d7685f8f0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
